### ISSUE TITLE
Uploading images broken?

### ISSUE THREAD

**Issue by derianlebreton** [concubidated/garage#3]
![image](https://user-images.githubusercontent.com/71905582/166060508-d4b55e61-bf05-4180-b07c-4efcd26fa344.png)

Uploading an image appears to work (via select file or drag and drop), but the box in the corner is stuck at "Uploading..." and never recovers.  This screen cannot be exited from except by hitting back or closing the browser tab.

**Comment by concubidated** [comment]
Fixed
